alias: dummy-problem

# if true, ignores the .outs and uses the solution
# to generate them from the .ins
generate-output: true
solution: solution/solution.cpp
# timeout for .out generator per .in
timeout: 0.5

# create the problem if it isn't already in omegaUp
create: true

# all of these are optional unless create is set to true
params:
  title: Comida Fr√≠a
  source: Curso OMI (Orac)

  visibility: 1

  # valid options: all, karel
  languages: all

  time_limit: 1000
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  # valid options: token-caseless, token-numeric, token-numeric, custom, literal
  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
